services:
  mysql:
    image: mysql:8.0
    container_name: client-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: client_db
    ports:
      - "3308:3306" 
    networks:
      - microservices
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  mysql-product:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"  # cambia el puerto externo para evitar conflicto
    networks:
      - microservices
    volumes:
      - mysql_product_data:/var/lib/mysql
    restart: always

networks:
  microservices:
    driver: bridge

volumes:
  mysql_data:
  mysql_product_data:

