spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_db
    username: root
    password: rootpassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8091