spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/coach_db
    username: root
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enabled: false
      
server:
  port: 8094